caches:
  lruMemCache:
    cacheName: lruMemCache
    cacheType: Memory
    evictionStrategy: LRU
    levelOneCacheSize: 5
  lfuMemCache:
    cacheName: lfuMemCache
    cacheType: Memory
    evictionStrategy: LFU
    levelOneCacheSize: 5
  lruCompositeCache:
    cacheName: lruCompositeCache
    cacheType: Composite
    evictionStrategy: LRU
    levelOneCacheSize: 5
    levelTwoCacheEnable: true
    levelTwoCacheSize: 5
    levelTwoCacheDir: "src/main/resources/cacheTest/lruCompositeCache"
  lfuCompositeCache:
    cacheName: lruCompositeCache
    cacheType: Composite
    evictionStrategy: LFU
    levelOneCacheSize: 5
    levelTwoCacheEnable: true
    levelTwoCacheSize: 5
    levelTwoCacheDir: "src/main/resources/cacheTest/lfuCompositeCache"



